instruments: 

 

  ivvi:
    type: qcodes_contrib_drivers.drivers.QuTech.IVVI.IVVI
    enable_forced_reconnect: true
    address: ASRL1
    init:
      name: ivvi
      dac_step: 15
      dac_delay: 0.03
      polarity: ['BIP', 'BIP', 'BIP', 'BIP']
      numdacs: 16
      use_locks: False #shall this be false to avoid erro on abort sweep?

  spi:
    type: core_tools.drivers.spi_rack.SPI_rack
    enable_forced_reconnect: true
    address: 'COM4'
    init:
      name: spi

  lia1:
    type: qcodes.instrument_drivers.stanford_research.SR830.SR830
    enable_forced_reconnect: true
    address: GPIB0::7::INSTR
    init:
      name: lia1

  lia2:
    type: qcodes.instrument_drivers.stanford_research.SR830.SR830
    enable_forced_reconnect: true
    address: GPIB0::8::INSTR
    init:
      name: lia2

  lia3:
    type: qcodes.instrument_drivers.stanford_research.SR830.SR830
    enable_forced_reconnect: true
    address: GPIB0::10::INSTR
    init:
      name: lia3

  
  keithley1: 
    type: qcodes_contrib_drivers.drivers.Tektronix.Keithley_2700.Keithley_2700
    enable_forced_reconnect: true
    address: GPIB0::15::INSTR
    init:
      name: keithley1

  keithley2: 
    type: qcodes_contrib_drivers.drivers.Tektronix.Keithley_2700.Keithley_2700
    enable_forced_reconnect: true
    address: GPIB0::16::INSTR
    init:
      name: keithley2

  keithley3: 
    type: qcodes_contrib_drivers.drivers.Tektronix.Keithley_6500.Keithley_6500
    enable_forced_reconnect: true
    address: USB0::0x05E6::0x6500::04472176::INSTR
    init:
      name: keithley3

  magnet:
    type: stations.Leiden.drivers.CryogenicSMS120C.CryogenicSMS120C
    enable_forced_reconnect: true
    address: ASRL21::INSTR

  temp_control: 
    type: stations.Leiden.drivers.DRTempControl.DRTempControl
    enable_forced_reconnect: true

  U2:
    type: stations.Leiden.drivers.U2QC.U2_moduleQC
    enable_forced_reconnect: true
    init:
      name: 'U2'
      module: 1
      inter_delay: 0.001
      dac_step: 10e-3
      reset_voltages: False
      mV: False
      number_dacs: 8

  cryomux:
    type: stations.Leiden.drivers.cryomux.CryogenicMultiplexer
    enable_forced_reconnect: true
    init:
      name: 'cryomux'
      U2_instr_name: 'U2'


 ############################
  mock_dac:
    type: qcodes.tests.instrument_mocks.DummyInstrument
    enable_forced_reconnect: true
    init:
      # To pass an list of items use {}.
      gates: {"ch1", "ch2"}
    add_parameters:
      Bx: {source: ch1, label: Bx, unit: T,
           scale: 28, limits: [-1, 1], monitor: true}
 

  mock_Rmeas:
    type: dummy_instrument.Dummy_R_measure
    enable_forced_reconnect: true


  # ivvi:
  #   type: qcodes_contrib_drivers.drivers.QuTech.IVVI.IVVI
  #   address: ASRL1::INSTR
  #   enable_forced_reconnect: true

  #   init:
  #     update_currents: false
  #     dac_step: 15
  #     dac_delay: 0.01
  #     polarity: ['BIP', 'BIP', 'BIP', 'BIP']
  #     numdacs: 16
  #     use_locks: True)