instruments: 

  dmm1:
    type: qcodes.instrument_drivers.agilent.Agilent_34400A.Agilent_34400A
    enable_forced_reconnect: true
    address: GPIB::1::65535::INSTR
    init:
      visalib: 'Agilent_34400A.yaml@sim'
    parameters:
      volt: {monitor: true}
 
  mock_dac:
    type: qcodes.tests.instrument_mocks.DummyInstrument
    enable_forced_reconnect: true
    init:
      # To pass an list of items use {}.
      gates: {"ch1", "ch2"}
    add_parameters:
      Bx: {source: ch1, label: Bx, unit: T,
           scale: 28, limits: [-1, 1], monitor: true}
 
  mock_dac2:
    type: qcodes.tests.instrument_mocks.DummyInstrument
    enable_forced_reconnect: true

  mock_parabola: 
    type: qcodes.tests.instrument_mocks.MockParabola
    enable_forced_reconnect: true

  mock_Rmeas:
    type: dummy_instrument.Dummy_R_measure
    enable_forced_reconnect: true



  # ivvi:
  #   type: qcodes_contrib_drivers.drivers.QuTech.IVVI.IVVI
  #   address: ASRL1::INSTR
  #   enable_forced_reconnect: true

  #   init:
  #     update_currents: false
  #     dac_step: 15
  #     dac_delay: 0.01
  #     polarity: ['BIP', 'BIP', 'BIP', 'BIP']
  #     numdacs: 16
  #     use_locks: True)